ScrollUp, search and sorting button
Sanae-G/CapstoneProject pull request #18
Opened 2022-05-16 13:29 UTC by Sanae-G

2022-05-16 16:49 UTC, anitaschiller requested changes
Hi Sanae! 
I left some comments but overall a good job 😊. Did you already think about deploying your app? Would be easier to review and try out stuff.

2022-05-16 16:49 UTC, anitaschiller commented on client/src/components/SortButton.js
> +  console.log(chronological);
There's a leftover console.log!

2022-05-16 16:49 UTC, anitaschiller commented on client/src/components/SearchInput.js
> +  // const [searchButtonState, setSearchButtonState] = useState(false);
Can be deleted if you don't use it anymore!

2022-05-16 16:49 UTC, anitaschiller commented on client/src/components/ScrollUpButton.js
> +  }, []);
I couldn't try it unfortunately (would be easier if the app was deployed 😉) but what happens if you scroll up and down without doing a reload in between? Does the button re-appear when you scroll below 300 on the y-axis?

2022-05-16 16:49 UTC, anitaschiller commented on client/src/components/ScrollUpButton.js
> +// import styled from 'styled-components';
Can be deleted!

2022-05-17 08:07 UTC, Sanae-G commented on client/src/components/Header/JournalHeader.js
> +  background-color: ${({ color }) => color};
This is for storybook. There you can change the color of the header.

2022-05-17 08:08 UTC, Sanae-G commented on client/src/components/PostCard/PostCard.js
> +            {post.img !== '' ? <img src={post.img} width="150px" alt="moment"></img> : ''}
Thank you very much. I forgot this approach! :)

2022-05-17 08:19 UTC, Sanae-G commented on client/src/components/ScrollUpButton.js
> +  }, []);
Yes it does! :D At least on firefox! xD I will deploy my app today! ^^

2022-05-17 08:27 UTC, merged